### ISSUE TITLE
Archiving this repository

### ISSUE THREAD

**Issue by jmcarcell** [key4hep/k4Pandora#8]
Hello @wenxingfang and @mirguest 
This repository doesn't build and probably hasn't been buildable for some time with the current key4hep stack. Since it has not been developed in more than two years, can we archive it?

**Comment by wenxingfang** [comment]
@jmcarcell , currently, we have no manpower to maintain the package. I think we can archive the package first. When we get manpower or someone wants to contribute, we can unarchive and update it.

**Comment by jmcarcell** [comment]
Sounds good, I'm archiving it until there is someone maintaining it
